import Head from 'next/head'

import { Typography,Button } from '@mui/material';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button variant="contained" className="w-full">Hello G</Button>
        <Typography className="underline">
          Welcome to Next.js!
        </Typography>
    </main>
    </div>
  )
}
